apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-namespace-pods
spec:
  # Apply to all localcoda backend pods in this namespace
  podSelector:
    matchExpressions:
    - key: localcoda-instanceid
      operator: Exists
  policyTypes:
  - Egress
  egress:
  - to:
    # Allow traffic to internet (but not internal kubernetes network)
    - ipBlock:
        cidr: '0.0.0.0/0'
        except: ['10.0.0.0/8']
