#!/bin/bash
#Mimic a blocking entrypoint, waiting for the blockingpid to be killed. Allows to fake a shutdown.
/etc/localcoda/entrypoint.sh
mkfifo /etc/localcoda/entrypoint-blocking.pause 2>/dev/null
read < /etc/localcoda/entrypoint-blocking.pause
exit 0
